export const GET_PRODUCT_ITEM_REQ = "GET_PRODUCT_ITEM_REQ";
export const GET_PRODUCT_ITEM_SUCCESS = "GET_PRODUCT_ITEM_SUCCESS";
export const GET_PRODUCT_ITEM_FAIL = "GET_PRODUCT_ITEM_FAIL";

export const SIGN_UP_REQ = "SIGN_UP_REQ";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const SIGN_IN_REQ = "SIGN_IN_REQ";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";
export const LOG_OUT = "LOG_OUT";
